--- 
- 
  become: true
  hosts: dev
  tasks: 
    - 
      command: "{{ item }}"
      name: "install docker"
      with_items: 
        - "sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo"
        - "sudo dnf install docker-ce --nobest -y"
        - "sudo systemctl enable docker"
        - "sudo systemctl start docker"
        - "sudo dnf install python3-pip -y"
        - "pip3 install docker-py"
    - 
      docker_container: 
        image: "sahilthakre123/sampleapp:{{DOCKER_TAG}}"
        name: sampleapp
        published_ports: 
          - "0.0.0.0:8553:8080"
        state: started
